global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'java'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['java:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']