{
 "title": "Monitoramento de Rotas Spring Boot",
 "tags": [
  "Spring Boot",
  "HTTP",
  "Routes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "rota",
    "label": "Selecione a Rota",
    "query": "label_values(http_server_requests_seconds_count, uri)"
   },
   {
    "name": "pool",
    "label": "Selecione o Pool",
    "query": "label_values(hikaricp_connections_active, pool)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Número de Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"$rota\"}[1m])) by (method, status)",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Latência Média (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=\"$rota\"}[1m])) by (method) / sum(rate(http_server_requests_seconds_count{uri=\"$rota\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latência Máxima (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri=\"$rota\"}",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Taxa de Sucesso",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"$rota\", outcome=\"SUCCESS\"}[1m])) / sum(rate(http_server_requests_seconds_count{uri=\"$rota\"}[1m])) * 100",
     "legendFormat": "Taxa de Sucesso (%)"
    }
   ]
  },
  {
   "title": "Saturação do Pool",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"$pool\"} / hikaricp_connections_max{pool=\"$pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Conexões Máx/Min",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{pool=\"$pool\"}",
     "legendFormat": "Máx"
    },
    {
     "expr": "hikaricp_connections_min{pool=\"$pool\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Conexões Ociosas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "targets": [
    {
     "expr": "hikaricp_connections_idle{pool=\"$pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Conexões Ativas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pool=\"$pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tempo para pegar conexão (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{pool=\"$pool\"} / hikaricp_connections_acquire_seconds_count{pool=\"$pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tempo de uso das conexões (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{pool=\"$pool\"} / hikaricp_connections_usage_seconds_count{pool=\"$pool\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}